### ISSUE TITLE
[ADDITION] Aseprite (Complete)

### ISSUE THREAD

**Issue by gudorlltti** [Lissy93/awesome-privacy#223]
### Category

Creativity

### Listing Name

Aseprite

### Listing URL

https://www.aseprite.org/

### Listing Icon

https://upload.wikimedia.org/wikipedia/commons/2/24/Logo_Aseprite.png

### Listing Description

An animated sprite editor & pixel art tool for Windows, macOS and Linux.

### GitHub repository

https://github.com/aseprite/aseprite

### Is Open Source?

- [X] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> It is a very well known pixel art editor (paid, but open-source).
> 
> TOS: https://www.aseprite.org/terms/
> 
> PRIVACY:https://www.aseprite.org/privacy/
> 
> I am not associated with them but i think it is a great application!
> 
> Haven't found any discussions/PRs for it.

**YAML Content for Addition**

```yaml
- name: Aseprite
  url: https://www.aseprite.org/
  icon: https://upload.wikimedia.org/wikipedia/commons/2/24/Logo_Aseprite.png
  description: An animated sprite editor & pixel art tool for Windows, macOS and Linux.
  github: https://github.com/aseprite/aseprite
  tosdrId: ''
  openSource: true
  securityAudited: false
  acceptsCrypto: false

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I have clearly declared any affiliation I may have with this service
