### ISSUE TITLE
[ADDITION] Brave Search (Complete)

### ISSUE THREAD

**Issue by stepersy** [Lissy93/awesome-privacy#226]
### Category

Essentials

### Listing Name

Brave Search

### Listing URL

https://search.brave.com/

### Listing Icon

https://i.ibb.co/GH1n4wf/Brave-Search-Icon.png

### Listing Description

Brave Search is a privacy-focused search engine that does not track users or their searches, does not use secret algorithms or user profiling, and is based on its own search index.

### GitHub repository

brave/brave-browser

### ToS;DR ID

1487

### Is Open Source?

- [X] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> Brave Search should be included in this list because it's private, based on its own index and made by the Brave Company, which browser is already included in this website.
> 
> Heree it is their privacy policy and ToS:
> https://search.brave.com/help/privacy-policy
> https://brave.com/terms-of-use/
> 
> I'm not involved with the company. I'm just a student from Italy who uses this search engine every day and I find it strange that it's not already on the list.
> 
> https://www.youtube.com/watch?v=-W2M9-B4NtM
> https://www.youtube.com/watch?v=ma2qDOkvaJo

**YAML Content for Addition**

```yaml
- name: Brave Search
  url: https://search.brave.com/
  icon: https://i.ibb.co/GH1n4wf/Brave-Search-Icon.png
  description: >-
    Brave Search is a privacy-focused search engine that does not track users or
    their searches, does not use secret algorithms or user profiling, and is
    based on its own search index.
  github: brave/brave-browser
  tosdrId: 1487
  iosApp: https://apps.apple.com/us/app/brave-private-browser-adblock/id1052879175
  androidApp: https://play.google.com/store/apps/details?id=com.brave.browser
  discordInvite: ''
  subreddit: r/brave_browser
  openSource: true
  securityAudited: true
  acceptsCrypto: false

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I have clearly declared any affiliation I may have with this service
