### ISSUE TITLE
[ADDITION] Resulti (Complete)

### ISSUE THREAD

**Issue by jacobi090** [Lissy93/awesome-privacy#227]
### Category

Essentials

### Listing Name

Resulti

### Listing URL

https://resulti.net

### Listing Icon

https://resulti.net/assets/icon.png

### Listing Description

Resulti is a private and security focused search engine based in Canada, Province of Quebec. The search engine is also Family-friendly by filtering adults websites.

### GitHub repository

no github

### Is Open Source?

- [ ] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> Resulti is a very good search engine that respect the privacy and also do not propose any dangerous website. Resulti is one of the rarest search engine that also focus on being family-friendly for children that use the web. Also, canadian search engines are rare, only presearch is canadian. since im also canadian, i want to contribute too by addings canadian services such as search engine, apps etc. If needed, im the creator of this project. Also sorry for the github question. We no longer have a github repo. 

**YAML Content for Addition**

```yaml
- name: Resulti
  url: https://resulti.net
  icon: https://resulti.net/assets/icon.png
  description: >-
    Resulti is a private and security focused search engine based in Canada,
    Province of Quebec. The search engine is also Family-friendly by filtering
    adults websites.
  github: 'no'
  securityAudited: true
  acceptsCrypto: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I have clearly declared any affiliation I may have with this service
