### ISSUE TITLE
[REMOVAL] Skiff Pages

### ISSUE THREAD

**Issue by Gemelovg** [Lissy93/awesome-privacy#228]
### Title

**Skiff Pages** (source: [Productivity ➜ Cloud Productivity Suites ➜ Skiff Pages](https://github.com/Lissy93/awesome-privacy/tree/main#cloud-productivity-suites))

### Removal Reason

Doesnt exist anymore.

### Removal Data

```yaml
name: Skiff Pages
url: https://skiff.com/pages
icon: https://skiff.com/favicon.ico
github: skiff-org/skiff-apps
followWith: Web, iOS, Android
tosdrId: 8470
description: |
  Skiff Pages is an end-to-end encrypted, privacy-first collaborative
  document, note-taking, and wiki product. Skiff Pages has a modern,
  easy-to-use UI and supports rich text documents with embedded content.
  Skiff also supports end-to-end encrypted file upload and sharing
  (Skiff Drive), as well as workspaces for multiple users to collaborate.
```

### Would you like to submit a PR?

None

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You have read our [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md) and software requirements
- [X] You agree to the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
