### ISSUE TITLE
[ADDITION] Pass (Complete)

### ISSUE THREAD

**Issue by dwisiswant0** [Lissy93/awesome-privacy#233]
### Category

Security Tools

### Listing Name

Pass

### Listing URL

https://www.passwordstore.org/

### Listing Icon

https://www.zx2c4.com/favicon.ico

### Listing Description

The Standard Unix Password Manager

### GitHub repository

https://git.zx2c4.com/password-store/

### ToS;DR ID

-2

### Is Open Source?

- [X] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> `pass` makes managing these individual password files extremely easy. All passwords live in `~/.password-store`, and pass provides some nice commands for adding, editing, generating, and retrieving passwords. It is a very short and simple shell script. It's capable of temporarily putting passwords on your clipboard and tracking password changes using `git`.

**YAML Content for Addition**

```yaml
- name: Pass
  url: https://www.passwordstore.org/
  icon: https://www.zx2c4.com/favicon.ico
  description: The Standard Unix Password Manager
  github: https://git.zx2c4.com/pass
  tosdrId: -2
  openSource: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I have clearly declared any affiliation I may have with this service
