### ISSUE TITLE
[ADDITION] Passbolt (Complete)

### ISSUE THREAD

**Issue by TheGuardianLight** [Lissy93/awesome-privacy#235]
### Category

Essentials

### Listing Name

Passbolt

### Listing URL

https://passbolt.com/

### Listing Icon

https://th.bing.com/th/id/OIP.G8UJD5A3g8WkhyqMuPotgAAAAA?rs=1&pid=ImgDetMain

### Listing Description

Opensource password manager with cloud-sync. It's simple to use and the community version is fully free to use.

### GitHub repository

https://github.com/passbolt/passbolt_api

### Is Open Source?

- [ ] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> It's a tool similar to Bitwarden that's opensource and has a free community version for anyone who wants to host it on their own server.

**YAML Content for Addition**

```yaml
- name: Passbolt
  url: https://passbolt.com/
  icon: https://th.bing.com/th/id/OIP.G8UJD5A3g8WkhyqMuPotgAAAAA?rs=1&pid=ImgDetMain
  description: >-
    Opensource password manager with cloud-sync. It's simple to use and the
    community version is fully free to use.
  github: https://github.com/passbolt/passbolt_api
  openSource: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I have clearly declared any affiliation I may have with this service
