### ISSUE TITLE
[ADDITION] Stalwart Mail Server (Complete)

### ISSUE THREAD

**Issue by TheSL18** [Lissy93/awesome-privacy#236]
### Category

Essentials

### Listing Name

Stalwart Mail Server

### Listing URL

https://stalw.art

### Listing Icon

https://github.com/stalwartlabs/mail-server/raw/main/img/logo-red.svg

### Listing Description

Self-hosting your mail server has been notoriously difficult. Not anymore! Stalwart is a scalable, secure and robust open-source mail server software designed for the 21st century. 

### GitHub repository

https://github.com/stalwartlabs/mail-server

### Is Open Source?

- [X] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> https://github.com/stalwartlabs

**YAML Content for Addition**

```yaml
- name: Stalwart Mail Server
  url: https://stalw.art
  icon: https://github.com/stalwartlabs/mail-server/raw/main/img/logo-red.svg
  description: >-
    Self-hosting your mail server has been notoriously difficult. Not anymore!
    Stalwart is a scalable, secure and robust open-source mail server software
    designed for the 21st century. 
  github: https://github.com/stalwartlabs/mail-server
  openSource: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I have clearly declared any affiliation I may have with this service
