### ISSUE TITLE
[ADDITION] qBittorrent (Complete)

### ISSUE THREAD

**Issue by Jackthemanyt** [Lissy93/awesome-privacy#237]
### Category

Essentials

### Listing Name

qBittorrent

### Listing URL

https://qBittorrent.org/

### Listing Icon

https://upload.wikimedia.org/wikipedia/commons/6/66/New_qBittorrent_Logo.svg

### Listing Description

Cross platform free and open source BitTorrent client written in C++

### GitHub repository

qbittorrent/qbittorrent

### Is Open Source?

- [X] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> Used by most
> Supports binding your vpn

**YAML Content for Addition**

```yaml
- name: qBittorrent
  url: https://qBittorrent.org/
  icon: https://upload.wikimedia.org/wikipedia/commons/6/66/New_qBittorrent_Logo.svg
  description: Cross platform free and open source BitTorrent client written in C++
  github: qbittorrent/qbittorrent
  openSource: true
  securityAudited: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I have clearly declared any affiliation I may have with this service
