### ISSUE TITLE
[AMENDMENT] Jmp.chat

### ISSUE THREAD

**Issue by singpolyma** [Lissy93/awesome-privacy#245]
### Title

**Jmp.chat** (source: [Communication ➜ Virtual Phone Numbers ➜ Jmp.chat](https://github.com/Lissy93/awesome-privacy/tree/main#virtual-phone-numbers))

### Amendments

Fix current price and note the service is no longer is beta

### Amendment Data

```yaml
name: Jmp.chat
url: https://jmp.chat/
icon: https://jmp.chat/static/jmp.svg
androidApp: com.cheogram.android.playstore
description: >
  Phone number for incoming + outgoing calls and messages, provided by Soprani.

  Works with Jabber, Matrix, Snikket, XMPP or any SIP client. Pricing starts at

  $4.99 / month. Only available in the US and Canada (as of 2024).

  See alternate instances at [soprani.ca](https://soprani.ca/)
```

### Affiliation Disclosure

Yes, I am affiliated with this project

### Would you like to submit a PR?

Maybe?

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with the project the amendment refers to
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software / service
- [X] You agree to our [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] You have read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
