### ISSUE TITLE
[ADDITION] Sharex (Complete)

### ISSUE THREAD

**Issue by arghya2801** [Lissy93/awesome-privacy#247]
### Category

Essentials

### Listing Name

Sharex

### Listing URL

https://getsharex.com/

### Listing Icon

https://i.imgur.com/51yazyq.png

### Listing Description

A free and open source screenshot tool for Windows. Provides a large amount of screenshot utilities, significantly more than the default OS tools. Also provides additional features like OCR, color picker, basic screen recording, annotations etc. 

### GitHub repository

https://github.com/ShareX/ShareX

### ToS;DR ID

3573

### Is Open Source?

- [ ] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> This is a fantastic open source utility for screenshots on Windows. Provides a large amount of screenshot utilities, significantly more than the default OS tools. Also provides additional features like OCR, color picker, basic screen recording, annotations etc. 
> 
> The privacy policy - https://getsharex.com/privacy-policy
> 
> I am not affiliated with this service. I just use this quite a lot.
> 
> 

**YAML Content for Addition**

```yaml
- name: Sharex
  url: https://getsharex.com/
  icon: https://i.imgur.com/51yazyq.png
  description: >-
    A free and open source screenshot tool for Windows. Provides a large amount
    of screenshot utilities, significantly more than the default OS tools. Also
    provides additional features like OCR, color picker, basic screen recording,
    annotations etc. 
  github: https://github.com/ShareX/ShareX
  tosdrId: 3573
  discordInvite: https://discord.gg/invite/ShareX
  subreddit: r/sharex/
  openSource: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I have clearly declared any affiliation I may have with this service
