### ISSUE TITLE
[ADDITION] SMSPool (Complete)

### ISSUE THREAD

**Issue by smspool** [Lissy93/awesome-privacy#249]
### Category

Essentials

### Listing Name

SMSPool

### Listing URL

https://smspool.net

### Listing Icon

https://www.smspool.net/android-chrome-512x512.png

### Listing Description

Protect your identity today with our one-time use or rental phone numbers.

### GitHub repository

https://github.com/smspool

### ToS;DR ID

10033

### Is Open Source?

- [ ] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [X] Yes, accept anonymous payment

### Justification and Further Info

> Add an option for TOR maybe? Since we support TOR.
> 
> https://github.com/Lissy93/awesome-privacy/issues/200

**YAML Content for Addition**

```yaml
- name: SMSPool
  url: https://smspool.net
  icon: https://www.smspool.net/android-chrome-512x512.png
  description: Protect your identity today with our one-time use or rental phone numbers.
  github: https://github.com/smspool
  tosdrId: 10033
  iosApp: https://apps.apple.com/us/app/smspool/id6474617801
  androidApp: https://play.google.com/store/apps/details?id=com.smspool.app&hl=en_US
  subreddit: smspool
  acceptsCrypto: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I have clearly declared any affiliation I may have with this service
