### ISSUE TITLE
[ADDITION] AdGuard Home (Complete)

### ISSUE THREAD

**Issue by SwissOS** [Lissy93/awesome-privacy#250]
### Category

Essentials

### Listing Name

AdGuard Home

### Listing URL

https://github.com/AdguardTeam/AdGuardHome

### Listing Icon

https://iconduck.com/icons/252880/adguard-home#

### Listing Description

Privacy protection center for you and your devices
Free and open source, powerful network-wide ads & trackers blocking DNS server. 

### GitHub repository

https://github.com/AdguardTeam/AdGuardHome

### Is Open Source?

- [X] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> This is an alternative to PiHole, with a more modern interface and secure upstream protocols. Very easy to install, also includes a docker image. For a full description including comparison to other solutions, check out their wiki at https://github.com/AdguardTeam/AdGuardHome/wiki

**YAML Content for Addition**

```yaml
- name: AdGuard Home
  url: https://github.com/AdguardTeam/AdGuardHome
  icon: https://iconduck.com/icons/252880/adguard-home#
  description: >-
    Privacy protection center for you and your devices

    Free and open source, powerful network-wide ads & trackers blocking DNS
    server. 
  github: https://github.com/AdguardTeam/AdGuardHome
  openSource: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I have clearly declared any affiliation I may have with this service
