### ISSUE TITLE
[AMENDMENT] NextDNS

### ISSUE THREAD

**Issue by Larssyyy** [Lissy93/awesome-privacy#254]
### Title

**NextDNS** (source: [Networking ➜ DNS Providers ➜ NextDNS](https://github.com/Lissy93/awesome-privacy/tree/main#dns-providers))

### Amendments

 Added More Info About What it does

### Amendment Data

```yaml
name: NextDNS
url: https://nextdns.io
icon: https://nextdns.io/favicon.ico
tosdrId: 1959
description: >
  An ad-blocking, privacy-protecting, censorship-bypassing DNS. Also comes with
  analytics, and the ability to shield kids from adult content it also comes with ai detection and blocking of new domains..
```

### Would you like to submit a PR?

Yes!

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with the project the amendment refers to
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software / service
- [X] You agree to our [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] You have read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
