### ISSUE TITLE
[ADDITION] /e/OS (Complete)

### ISSUE THREAD

**Issue by luxunwansui** [Lissy93/awesome-privacy#256]
### Category

Operating Systems

### Listing Name

/e/OS

### Listing URL

https://e.foundation/get-started/

### Listing Icon

https://e.foundation/wp-content/uploads/2022/11/e-logo-noir-01.png

### Listing Description

/e/OS is an open-source mobile operating system paired with carefully selected applications. They form a privacy-enabled internal system for your smartphone. And it’s not just claims: open-source means auditable privacy. /e/OS has received academic recognition from researchers at the University of Edinburgh and Trinity College of Dublin.

### GitHub repository

https://gitlab.e.foundation/e

### Is Open Source?

- [X] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [X] Yes, accept anonymous payment

### Justification and Further Info

> Ive tested it on my Android device and it performed as well as other privacy-oriented OSs. Pushing OTA updates are monthly.

**YAML Content for Addition**

```yaml
- name: /e/OS
  url: https://e.foundation/get-started/
  icon: https://e.foundation/wp-content/uploads/2022/11/e-logo-noir-01.png
  description: >-
    /e/OS is an open-source mobile operating system paired with carefully
    selected applications. They form a privacy-enabled internal system for your
    smartphone. And it’s not just claims: open-source means auditable privacy.
    /e/OS has received academic recognition from researchers at the University
    of Edinburgh and Trinity College of Dublin.
  github: https://gitlab.e.foundation/e
  subreddit: eeol
  openSource: true
  acceptsCrypto: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I have clearly declared any affiliation I may have with this service
