### ISSUE TITLE
[ADDITION] Notesnook (Complete)

### ISSUE THREAD

**Issue by ghost** [Lissy93/awesome-privacy#257]
### Category

Essentials

### Listing Name

Notesnook

### Listing URL

https://github.com/streetwriters/notesnook

### Listing Icon

https://raw.githubusercontent.com/streetwriters/notesnook/master/resources/icon.png

### Listing Description

Write notes with freedom, no spying, no tracking.

### GitHub repository

https://github.com/streetwriters

### ToS;DR ID

4148

### Is Open Source?

- [X] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> In my personal opinion, this app is something similar to Evernote(ui/ux), not like Evernote (closed source). There are several improvements to be made and several open issues, and I am closely following any changes or directions.
> I think it would be interesting for anyone to evaluate and see. Discussions are open: https://github.com/streetwriters/notesnook/discussions
> I'm thinking about contributing to Awesome Privacy, and I thought I'd include it here because that's what I found on GitHub for trending topics.

**YAML Content for Addition**

```yaml
- name: Notesnook
  url: https://github.com/streetwriters/notesnook
  icon: >-
    https://raw.githubusercontent.com/streetwriters/notesnook/master/resources/icon.png
  description: Write notes with freedom, no spying, no tracking.
  github: https://github.com/streetwriters
  tosdrId: 4148
  iosApp: https://github.com/streetwriters/notesnook/tree/master/apps/mobile
  androidApp: https://github.com/streetwriters/notesnook/tree/master/apps/mobile
  discordInvite: https://discord.com/invite/zQBK97EE22
  subreddit: https://www.reddit.com/r/notesnook
  openSource: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I have clearly declared any affiliation I may have with this service
