### ISSUE TITLE
[ADDITION] Spot-On Encryption Suite Messenger & Files (Complete)

### ISSUE THREAD

**Issue by Sammysupport** [Lissy93/awesome-privacy#259]
### Category

Communication

### Listing Name

Spot-On Encryption Suite Messenger & Files

### Listing URL

https://www.reddit.com/r/Spot_On_Encryption/

### Listing Icon

https://github.com/textbrowser/spot-on/blob/master/branches/trunk/Icons/Logo/spot-on-logo.png

### Listing Description

Spot-On is an open-source Encrpytion Suite for secure Chat & E-Mail, File Transfer and also Websearch in a F2F distributed URL-Database. Means: Spot-On is a Messaging & File-Transfer Software. With RSS you can import, read, search & distribute your feeds F2F to your friends over encrypted connections. Enhanced encryption processes have been invented & improved for implementation in Spot-On: such as McEliece-Messaging (Linux), Cryptographic Calling, Zero-Knowledge-Proofs, AutoCrypt etc.
Projektpage: https://github.com/textbrowser/spot-on
Screenshots: https://sammysupport.github.io/spot-on/

### GitHub repository

https://github.com/textbrowser/spot-on

### Is Open Source?

- [X] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

**YAML Content for Addition**

```yaml
- name: Spot-On Encryption Suite Messenger & Files
  url: https://www.reddit.com/r/Spot_On_Encryption/
  icon: >-
    https://github.com/textbrowser/spot-on/blob/master/branches/trunk/Icons/Logo/spot-on-logo.png
  description: >-
    Spot-On is an open-source Encrpytion Suite for secure Chat & E-Mail, File
    Transfer and also Websearch in a F2F distributed URL-Database. Means:
    Spot-On is a Messaging & File-Transfer Software. With RSS you can import,
    read, search & distribute your feeds F2F to your friends over encrypted
    connections. Enhanced encryption processes have been invented & improved for
    implementation in Spot-On: such as McEliece-Messaging (Linux), Cryptographic
    Calling, Zero-Knowledge-Proofs, AutoCrypt etc.

    Projektpage: https://github.com/textbrowser/spot-on

    Screenshots: https://sammysupport.github.io/spot-on/
  github: https://github.com/textbrowser/spot-on
  androidApp: https://f-droid.org/de/packages/org.purple.smoke/
  subreddit: https://www.reddit.com/r/Spot_On_Encryption/
  openSource: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I have clearly declared any affiliation I may have with this service
