### ISSUE TITLE
[REMOVAL] FilePizza

### ISSUE THREAD

**Issue by TheGuardianLight** [Lissy93/awesome-privacy#267]
### Title

**FilePizza** (source: [Productivity ➜ File Drop ➜ FilePizza](https://github.com/Lissy93/awesome-privacy/tree/main#file-drop))

### Removal Reason

The tool link is no longer available

### Removal Data

```yaml
name: FilePizza
url: https://file.pizza
github: kern/filepizza
followWith: Web
description: >
  Peer-to-peer based file transfer from the browser, using Web Torrent. It's
  quick and easy to use, and doesn't

  require any software to be installed. Can also be self-hosted.
```

### Association Disclosure

Not affiliated

### Would you like to submit a PR?

None

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You have read our [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md) and software requirements
- [X] You agree to the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
