### ISSUE TITLE
[ADDITION] DigiKam (Complete)

### ISSUE THREAD

**Issue by rr19-hub** [Lissy93/awesome-privacy#273]
### Category

Media

### Listing Name

DigiKam

### Listing URL

https://www.digikam.org/

### Listing Icon

https://www.digikam.org/img/digikam_oxygen.svg

### Listing Description

digiKam is an advanced open-source digital photo management application that runs on Linux, Windows, and macOS. The application provides a comprehensive set of tools for importing, managing, editing, and sharing photos and raw files.

### GitHub repository

https://invent.kde.org/graphics/digikam

### Is Open Source?

- [X] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> https://www.digikam.org/support/privacy_policy/

**YAML Content for Addition**

```yaml
- name: DigiKam
  url: https://www.digikam.org/
  icon: https://www.digikam.org/img/digikam_oxygen.svg
  description: >-
    digiKam is an advanced open-source digital photo management application that
    runs on Linux, Windows, and macOS. The application provides a comprehensive
    set of tools for importing, managing, editing, and sharing photos and raw
    files.
  github: https://invent.kde.org/graphics/digikam
  openSource: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I have clearly declared any affiliation I may have with this service
