### ISSUE TITLE
[AMENDMENT] ProtonMail

### ISSUE THREAD

**Issue by Chaman-veteran** [Lissy93/awesome-privacy#279]
### Title

**ProtonMail** (source: [Communication ➜ Encrypted Email ➜ ProtonMail](https://github.com/Lissy93/awesome-privacy/tree/main#encrypted-email))

### Amendments

ProtonMail's description starts with "An open-source..." but is flagged as "Not Open Source" which is quite ambiguous.  I suggest here to remove the open-source part of the introduction.

### Amendment Data

```yaml
name: ProtonMail
url: https://protonmail.com
icon: https://proton.me/favicons/android-chrome-192x192.png
openSource: false
github: ProtonMail/WebClients
tosdrId: 491
androidApp: ch.protonmail.android
iosApp: https://apps.apple.com/us/app/proton-mail-encrypted-email/id979659905
subreddit: ProtonMail
description: >
  An end-to-end encrypted anonymous email service. ProtonMail has a

  modern easy-to-use and customizable UI, as well as fast, secure native mobile

  apps. ProtonMail has all the features that you'd expect from a modern email

  service and is based on simplicity without sacrificing security. It has a free

  plan or a premium option for using custom domains (starting at $5/month).

  ProtonMail requires no personally identifiable information for signup, they
  have

  a [.onion](https://protonirockerxow.onion) server, for access via Tor, and
  they

  accept anonymous payment: BTC and cash (as well as the normal credit card and
  PayPal).
```

### Affiliation Disclosure

None

### Would you like to submit a PR?

Yes!

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with the project the amendment refers to
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software / service
- [X] You agree to our [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] You have read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
