### ISSUE TITLE
[AMENDMENT] ScriptSafe

### ISSUE THREAD

**Issue by Chaman-veteran** [Lissy93/awesome-privacy#281]
### Title

**ScriptSafe** (source: [Security Tools ➜ Browser Extensions ➜ ScriptSafe](https://github.com/Lissy93/awesome-privacy/tree/main#browser-extensions))

### Amendments

Fixed typo `Ppera` -> `Opera`

### Amendment Data

```yaml
name: ScriptSafe
url: https://www.andryou.com/scriptsafe
github: andryou/scriptsafe
icon: >-
  https://lh3.googleusercontent.com/c5co_NoLmEt48VC_yVp0JgKcgd83yiq_CdekGaOlBBfD5WII5mjxngERgikcQd4P56uoX9epiknU5ktXadPqj2EEVsE
description: >
  Allows you to block the execution of certain scripts. **Download**:

  [Chrome](https://chromewebstore.google.com/detail/scriptsafe/oiigbmnaadbkfbmpbfijlflahbdbdgdf)
  -

  [Opera](https://addons.opera.com/en/extensions/details/scriptsafe-2/)
```

### Affiliation Disclosure

None

### Would you like to submit a PR?

Yes!

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with the project the amendment refers to
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software / service
- [X] You agree to our [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] You have read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
