### ISSUE TITLE
[ADDITION] Picocrypt (Complete)

### ISSUE THREAD

**Issue by fstel** [Lissy93/awesome-privacy#291]
### Category

Essentials

### Listing Name

Picocrypt

### Listing URL

https://github.com/Picocrypt

### Listing Icon

https://raw.githubusercontent.com/Picocrypt/Picocrypt/refs/heads/main/images/key.ico

### Listing Description

Simple and secure file encryption for everyone.

### GitHub repository

https://github.com/Picocrypt

### Is Open Source?

- [X] Yes, it's open source

### Security Audited?

- [X] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> https://github.com/Picocrypt/storage/blob/main/Picocrypt.Audit.Report.pdf

**YAML Content for Addition**

```yaml
- name: Picocrypt
  url: https://github.com/Picocrypt
  icon: >-
    https://raw.githubusercontent.com/Picocrypt/Picocrypt/refs/heads/main/images/key.ico
  description: Simple and secure file encryption for everyone.
  github: https://github.com/Picocrypt
  openSource: true
  securityAudited: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I have clearly declared any affiliation I may have with this service
