### ISSUE TITLE
[ADDITION] Molly (Complete)

### ISSUE THREAD

**Issue by IssueMakerGit** [Lissy93/awesome-privacy#304]
### Category

Communication

### Listing Name

Molly

### Listing URL

https://molly.im/

### Listing Icon

https://www.privacyguides.org/en/assets/img/messengers/molly.svg

### Listing Description

Molly is a hardened version of Signal

### GitHub repository

https://github.com/mollyim

### Is Open Source?

- [X] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> I think a hardened version of signal would be a nice addition to either the signal page or having their own page.
> Privacy guides already has a page for it:
> https://www.privacyguides.org/en/real-time-communication/#molly-android

**YAML Content for Addition**

```yaml
- name: Molly
  url: https://molly.im/
  icon: https://www.privacyguides.org/en/assets/img/messengers/molly.svg
  description: Molly is a hardened version of Signal
  github: https://github.com/mollyim
  androidApp: https://github.com/mollyim/mollyim-android
  openSource: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I have clearly declared any affiliation I may have with this service
