### ISSUE TITLE
[ADDITION] Conversations (Complete)

### ISSUE THREAD

**Issue by MrEddX** [Lissy93/awesome-privacy#305]
### Category

Communication

### Listing Name

Conversations

### Listing URL

https://conversations.im/

### Listing Icon

https://conversations.im/images/conversations_logo.png

### Listing Description

Conversations is a Jabber/XMPP client for Android 5.0+ smartphones that has been optimized to provide a unique mobile experience.

### GitHub repository

https://codeberg.org/inputmice/Conversations

### Is Open Source?

- [X] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

Conversations is a strong candidate for inclusion in the Awesome Privacy due to its emphasis on privacy, open-source nature, and support for modern encryption protocols. Here are some key reasons why I think it should be considered:

- Developed and maintained by a community of open-source contributors, which further enhances trust and privacy
- Promotes and uses Decentralized XMPP network
- Allows users to have greater control over their privacy
- Free from ads, tracking, and data harvesting
- Not owned by a large company with vested commercial interests in mining user data or selling advertising
- Available for free from F-Droid: https://f-droid.org/en/packages/eu.siacs.conversations/

**YAML Content for Addition**

```yaml
- name: Conversations
  url: https://conversations.im/
  icon: https://conversations.im/images/conversations_logo.png
  description: >-
    Conversations is a Jabber/XMPP client for Android 5.0+ smartphones that has
    been optimized to provide a unique mobile experience.
  github: https://codeberg.org/inputmice/Conversations
  androidApp: https://play.google.com/store/apps/details?id=eu.siacs.conversations
  openSource: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I have clearly declared any affiliation I may have with this service
