### ISSUE TITLE
[REMOVAL] DivestOS

### ISSUE THREAD

**Issue by MrEddX** [Lissy93/awesome-privacy#306]
### Title

**DivestOS** (source: [Operating Systems ➜ Mobile Operating Systems ➜ DivestOS](https://github.com/Lissy93/awesome-privacy/tree/main#mobile-operating-systems))

### Removal Reason

After ten years of dedication and hard work, DivestOS is officially discontinued. A heartfelt thanks to Tavi for his invaluable work. Wish you all the best in your future endeavors!

### Removal Data

```yaml
name: DivestOS
url: https://divestos.org
icon: https://divestos.org/images/favicon.png
github: Divested-Mobile/DivestOS-Build
tosdrId: 2550
description: >
  DivestOS is a vastly diverged unofficial more secure and private soft fork of
  LineageOS. DivestOS primary goal is prolonging the life-span of 

  discontinued devices, enhancing user privacy, and providing a modest increase
  of security where/when possible. Project is developed and maintained 

  solely by Tad (SkewedZeppelin) since 2014.
```

### Would you like to submit a PR?

None

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You have read our [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md) and software requirements
- [X] You agree to the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
