### ISSUE TITLE
[ADDITION] LNP2P (Complete)

### ISSUE THREAD

**Issue by gnome801** [Lissy93/awesome-privacy#309]
### Category

Essentials

### Listing Name

LNP2P

### Listing URL

https://lnp2pbot.com/

### Listing Icon

https://lnp2pbot.com/img/logo.png

### Listing Description

Lnp2pBot is a bitcoin exchange system for local currency, enabling easy and secure person-to-person transactions using Lightning Network. It is a Telegram bot that can be used pseudonymously, without user registration or identity verification. This tool only holds satoshis (the smallest unit of bitcoin) for the minimum necessary time, providing greater security to users compared to exchange services with internal wallets and complete custody of funds. Lnp2pBot is an open-source application, allowing for auditing, replication, modification, and redistribution with freedom.

### GitHub repository

https://github.com/lnp2pBot

### ToS;DR ID

10801

### Is Open Source?

- [ ] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> Amazing Bitcoin p2p non-kyc exchange using lightning network which is 100x more private than Bitcoin. 

**YAML Content for Addition**

```yaml
- name: LNP2P
  url: https://lnp2pbot.com/
  icon: https://lnp2pbot.com/img/logo.png
  description: >-
    Lnp2pBot is a bitcoin exchange system for local currency, enabling easy and
    secure person-to-person transactions using Lightning Network. It is a
    Telegram bot that can be used pseudonymously, without user registration or
    identity verification. This tool only holds satoshis (the smallest unit of
    bitcoin) for the minimum necessary time, providing greater security to users
    compared to exchange services with internal wallets and complete custody of
    funds. Lnp2pBot is an open-source application, allowing for auditing,
    replication, modification, and redistribution with freedom.
  github: https://github.com/lnp2pBot
  tosdrId: 10801
  openSource: true
  acceptsCrypto: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [x] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [x] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I have clearly declared any affiliation I may have with this service
