### ISSUE TITLE
[ADDITION] Mullvad Browser (Complete)

### ISSUE THREAD

**Issue by 0w0v** [Lissy93/awesome-privacy#313]
### Category

Essentials

### Listing Name

Mullvad Browser

### Listing URL

https://mullvad.net/en/browser

### Listing Icon

https://mullvad.net/_app/immutable/assets/logo.Ba5MUFAA.svg

### Listing Description

Mullvad Browser is a privacy-focused web browser developed by the makers of Mullvad VPN in collaboration with the Tor Project. It is designed to minimize tracking and fingerprinting without requiring the Tor network. The browser provides strong anti-fingerprinting protections similar to the Tor Browser.

### GitHub repository

https://gitlab.torproject.org/tpo/applications/mullvad-browser/

### Is Open Source?

- [x] Yes, it's open source

### Security Audited?

- [x] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> 

**YAML Content for Addition**

```yaml
- name: Mullvad Browser
  url: https://mullvad.net/en/browser
  icon: https://mullvad.net/_app/immutable/assets/logo.Ba5MUFAA.svg
  description: >-
    Mullvad Browser is a privacy-focused web browser developed by the makers of
    Mullvad VPN in collaboration with the Tor Project. It is designed to
    minimize tracking and fingerprinting without requiring the Tor network. The
    browser provides strong anti-fingerprinting protections similar to the Tor
    Browser.
  github: https://gitlab.torproject.org/tpo/applications/mullvad-browser/
  openSource: true
  securityAudited: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [x] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [x] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I have clearly declared any affiliation I may have with this service
