### ISSUE TITLE
[ADDITION] Zen Browser (Complete)

### ISSUE THREAD

**Issue by 0w0v** [Lissy93/awesome-privacy#314]
### Category

Essentials

### Listing Name

Zen Browser

### Listing URL

https://zen-browser.app/

### Listing Icon

https://github.com/zen-browser/desktop/raw/dev/docs/assets/zen-dark.svg

### Listing Description

Zen is a privacy-focused browser that blocks trackers, ads, and other unwanted content while offering the best browsing experience!

### GitHub repository

zen-browser/desktop

### Is Open Source?

- [x] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> 

**YAML Content for Addition**

```yaml
- name: Zen Browser
  url: https://zen-browser.app/
  icon: https://github.com/zen-browser/desktop/raw/dev/docs/assets/zen-dark.svg
  description: >-
    Zen is a privacy-focused browser that blocks trackers, ads, and other
    unwanted content while offering the best browsing experience!
  github: zen-browser/desktop
  subreddit: zen_browser
  openSource: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [x] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [x] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I have clearly declared any affiliation I may have with this service
