### ISSUE TITLE
[ADDITION] Aidoku (Complete)

### ISSUE THREAD

**Issue by Googolplexed0** [Lissy93/awesome-privacy#315]
### Category

Media

### Listing Name

Aidoku

### Listing URL

https://aidoku.app/

### Listing Icon

https://aidoku.app/images/aidoku.svg

### Listing Description

A free, open source, manga reading application for iOS and iPadOS. Available via Apple's TestFlight program or through sideloading.

### GitHub repository

Aidoku/Aidoku

### Is Open Source?

- [x] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

> The app respects user privacy, does not collect user analytics, and has no ads. It serves as an alternative to standard manga reader apps that require an account and/or payment. It is actively maintained and actively promotes the freedom of information dissemination. I am not affiliated with the service (beyond being a user). Licensing, relevant discussions, past issues, and PRs can all be found on the GitHub and Discord channels.

**YAML Content for Addition**

```yaml
- name: Aidoku
  url: https://aidoku.app/
  icon: https://aidoku.app/images/aidoku.svg
  description: >-
    A free, open source, manga reading application for iOS and iPadOS. Available
    via Apple's TestFlight program or through sideloading.
  github: Aidoku/Aidoku
  discordInvite: 9U8cC5Zk3s
  subreddit: Aidoku
  openSource: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [x] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [x] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I have clearly declared any affiliation I may have with this service
