### ISSUE TITLE
[ADDITION] Skhron (Complete)

### ISSUE THREAD

**Issue by g00g1** [Lissy93/awesome-privacy#319]
### Category

Networking

### Listing Name

Skhron

### Listing URL

https://skhron.eu/

### Listing Icon

https://skhron.com.ua/assets/img/logo-square.png

### Listing Description

Skhron offers reliable privacy-first VPS. Uses own hardware and operates own network. Accepts Bitcoin (+ Lightning Network), Monero and other cryptocurrencies. No KYC required.

### GitHub repository

not applicable

### Is Open Source?

- [ ] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [x] Yes, accept anonymous payment

### Justification and Further Info

> - I am founder of Skhron
> - Skhron has Tor mirror for all customer-facing portals (billing, virtual machine management panel, etc)
> - Skhron accepts all cryptocurrencies using self-hosted gateways (BTCPay Server and Bitcart)
> - Skhron has a good history of customers' review (a few links available at https://skhron.eu/about-us page)
> - Terms of Service: https://skhron.eu/legal/terms-of-service
> - Privacy Policy: https://skhron.eu/legal/privacy-policy

**YAML Content for Addition**

```yaml
- name: Skhron
  url: https://skhron.eu/
  icon: https://skhron.com.ua/assets/img/logo-square.png
  description: >-
    Skhron reliable privacy-first VPS, uses own hardware and operates own
    network. Accepts Bitcoin (+ Lightning Network), Monero and other
    cryptocurrencies. No KYC required.
  github: not applicable
  acceptsCrypto: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [x] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [x] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I have clearly declared any affiliation I may have with this service
