### ISSUE TITLE
[ADDITION] Mullvad Browser (Complete)

### ISSUE THREAD

**Issue by privacy-first** [Lissy93/awesome-privacy#325]
### Category

Essentials

### Listing Name

Mullvad Browser

### Listing URL

https://mullvad.net/en/download/browser/

### Listing Icon

https://play-lh.googleusercontent.com/X3V8MJMnYasSOTLeFAN-EX8vKrckT2kxnPSeKRyGEU77pa-PVOjvKSvMdcOhnHX9aEg=w480-h960

### Listing Description

The Mullvad Browser is developed – in collaboration between Mullvad VPN and the Tor Project – to minimize tracking and fingerprinting.

### GitHub repository

https://github.com/mullvad/mullvad-browser

### Is Open Source?

- [x] Yes, it's open source

### Security Audited?

- [x] Yes, it's been security audited

### Accepts Anon Payment?

- [x] Yes, accept anonymous payment

### Justification and Further Info

> 

**YAML Content for Addition**

```yaml
- name: Mullvad Browser
  url: https://mullvad.net/en/download/browser/
  icon: >-
    https://play-lh.googleusercontent.com/X3V8MJMnYasSOTLeFAN-EX8vKrckT2kxnPSeKRyGEU77pa-PVOjvKSvMdcOhnHX9aEg=w480-h960
  description: >-
    The Mullvad Browser is developed – in collaboration between Mullvad VPN and
    the Tor Project – to minimize tracking and fingerprinting.
  github: https://github.com/mullvad/mullvad-browser
  openSource: true
  securityAudited: true
  acceptsCrypto: true

```

<sup>This ticket was submitted via <a href="https://awesome-privacy.xyz/submit">awesome-privacy.xyz/submit</a></sup>

### Final Checklist

- [x] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [x] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I have clearly declared any affiliation I may have with this service
